FROM php:8.2-fpm

RUN apt-get update && apt-get install -y \
    git   \
    curl  \
    zip \
    unzip

WORKDIR /var/www


FROM php:7.4-fpm


RUN apt-get update \
    && apt-get install -y \
       libzip-dev \
       zip \
       unzip \
       default-mysql-client \
    && docker-php-ext-install mysqli pdo_mysql zip

COPY ./ /var/www/


WORKDIR /var/www/


CMD ["php-fpm"]
